CREATE TABLE kartan_farmer_transaction (
    id BIGSERIAL PRIMARY KEY,
    sub_district_code VARCHAR(10) NOT NULL,
    district_code VARCHAR(6) NOT NULL,
    city_code VARCHAR(4) NOT NULL,
    province_code VARCHAR(2) NOT NULL,
    nik VARCHAR(16) NOT NULL,
    nama_petani VARCHAR(150) NOT NULL,
    urea NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    npk NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    sp36 NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    za NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    npk_formula NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    organic NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    poc NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    create_by INTEGER,
    ket VARCHAR(200),
    stat_kirim SMALLINT NOT NULL DEFAULT 3,
    nama_kios VARCHAR(255),
    tgl_tebus SMALLINT NOT NULL,
    bulan_tebus SMALLINT NOT NULL,
    tahun_tebus INTEGER NOT NULL,
    tgl_bank VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    tgl_kirim VARCHAR(255),
    src SMALLINT NOT NULL DEFAULT 1,
    txn_mid VARCHAR(255) NOT NULL,
    ref_code VARCHAR(255) NOT NULL,
    prov VARCHAR(255),
    kab VARCHAR(255),
    kec VARCHAR(255),
    desa VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    komoditas VARCHAR(50),
    poktan_id INTEGER,
    poktan_nama VARCHAR(255),
    refnum VARCHAR(200),
    id_wallet INTEGER
);